default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: 5

development:
  <<: *default
  database: ocr_feature_development

test:
  <<: *default
  database: ocr_feature_test

# On Heroku and other platform providers, you may have a full connection URL
# available as an environment variable. For example:
#
#   DATABASE_URL="postgres://myuser:mypass@localhost/somedatabase"
#
# You can use this database configuration with:
#
#   production:
#     url: <%= ENV['DATABASE_URL'] %>
#
# production:
#   <<: *default
#   database: ocr_feature_production
#   username: ocr_feature
#   password: <%= ENV['OCR_FEATURE_DATABASE_PASSWORD'] %>
